version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: clooky3000/exemple
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Testing docker image
          command: docker run --rm -d --name=test -p 8080:8080 $IMAGE_NAME:latest && docker ps --last=1 && docker stop test
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            cat ~/my_password.txt | docker login -u "clooky3000" --password-stdin
            docker push $IMAGE_NAME:latest

